import{a as S,S as P,i as c}from"./assets/vendor-BjRz3xa9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="49391267-a4a459152a4326aa641ed2d74",E="https://pixabay.com/api/";let h=1;const f=async(r,e)=>{try{const s=await S.get(E,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}});return h+=1,{hits:s.data.hits,totalHits:s.data.totalHits}}catch(s){throw console.error("Error fetching images",s),s}},I=()=>{h=1},d=document.querySelector(".gallery"),u=document.querySelector(".loader"),m=document.querySelector(".load-more"),y=document.querySelector(".end-message");document.addEventListener("DOMContentLoaded",()=>{u.classList.add("hidden"),y.classList.add("hidden"),m.classList.add("hidden")});const p=()=>{u.classList.remove("hidden")},L=()=>{u.classList.add("hidden")},$=()=>{d.innerHTML=""},w=r=>{const e=r.map(a=>`
        <li class="gallery-item">
          <a href="${a.largeImageURL}">
            <img class="gallery-img" src="${a.webformatURL}" alt="${a.tags}" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${a.likes}</p>
            <p><b>Views</b> ${a.views}</p>
            <p><b>Comments</b> ${a.comments}</p>
            <p><b>Downloads</b> ${a.downloads}</p>
          </div>
        </li>`).join("");d.insertAdjacentHTML("beforeend",e),new P(".gallery a").refresh(),m.classList.remove("hidden")},b=()=>{m.classList.add("hidden"),y.classList.remove("hidden")},M=()=>{iziToast.error({title:"Sorry, no images found",message:"Please try again with a different search term."})},H=()=>{const r=d.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})};let n="",i=1;const v=document.querySelector(".form"),g=v.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");v.addEventListener("submit",async r=>{if(r.preventDefault(),n=g.value.trim(),!n){c.error({title:"Input error",message:"Please enter a search term."});return}g.value="",I(),i=1,p(),$();try{const{hits:e,totalHits:s}=await f(n,i);e.length===0?M():(w(e),(e.length<15||e.length>=s)&&b())}catch{c.error({title:"Error",message:"Something went wrong. Please try again."})}finally{L()}});O.addEventListener("click",async()=>{p();try{i+=1;const{hits:r,totalHits:e}=await f(n,i);r.length>0&&(w(r),H(),(r.length<15||r.length>=e)&&b())}catch{c.error({title:"Error",message:"Something went wrong. Please try again."})}finally{L()}});
//# sourceMappingURL=index.js.map
