import{a as P,S as q,i}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const E="49391267-a4a459152a4326aa641ed2d74",I="https://pixabay.com/api/";let f=1;const y=async(e,r)=>{try{const o=await P.get(I,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return f+=1,{hits:o.data.hits,totalHits:o.data.totalHits}}catch(o){throw console.error("Error fetching images",o),o}},M=()=>{f=1},h=document.querySelector(".gallery"),m=document.querySelector(".loader"),l=document.querySelector(".load-more"),p=document.querySelector(".end-message");document.addEventListener("DOMContentLoaded",()=>{m.classList.add("hidden"),p.classList.add("hidden"),l.classList.add("hidden")});const L=()=>{m.classList.remove("hidden")},w=()=>{m.classList.add("hidden")},$=()=>{h.innerHTML=""},b=e=>{const r=e.map(a=>`<li class="gallery-item">
          <a href="${a.largeImageURL}">
            <img class="gallery-img" src="${a.webformatURL}" alt="${a.tags}" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${a.likes}</p>
            <p><b>Views</b> ${a.views}</p>
            <p><b>Comments</b> ${a.comments}</p>
            <p><b>Downloads</b> ${a.downloads}</p>
          </div>
        </li>`).join("");h.insertAdjacentHTML("beforeend",r),new q(".gallery a").refresh(),l.classList.remove("hidden")},u=(e=!1)=>{e?(l.classList.add("hidden"),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):(l.classList.remove("hidden"),p.classList.add("hidden"))},H=()=>{i.error({title:"Sorry, no images found",message:"Please try again with a different search term."}),l.classList.add("hidden")},O=()=>{const e=h.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})};let c="",n=1;const v=document.querySelector(".form"),g=v.querySelector('input[name="search-text"]'),S=document.querySelector(".load-more");v.addEventListener("submit",async e=>{if(e.preventDefault(),c=g.value.trim(),!c){i.error({title:"Input error",message:"Please enter a search term."});return}g.value="",M(),n=1,L(),$(),u(!1);try{const{hits:r,totalHits:o}=await y(c,n);r.length===0?H():(b(r),r.length>=o?u(!0):S.classList.remove("hidden"))}catch{i.error({title:"Error",message:"Something went wrong. Please try again."})}finally{w()}});S.addEventListener("click",async()=>{L();try{n+=1;const{hits:e,totalHits:r}=await y(c,n);e.length>0&&(b(e),O(),e.length+(n-1)*15>=r&&u(!0))}catch{i.error({title:"Error",message:"Something went wrong. Please try again."})}finally{w()}});
//# sourceMappingURL=index.js.map
