import{a as v,S as q,i as d}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const P="49391267-a4a459152a4326aa641ed2d74",E="https://pixabay.com/api/";let h=1;const f=async(e,t)=>{try{const o=await v.get(E,{params:{key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}});return h+=1,{hits:o.data.hits,totalHits:o.data.totalHits}}catch(o){throw console.error("Error fetching images",o),o}},I=()=>{h=1},m=document.querySelector(".gallery"),n=document.querySelector(".loader"),g=document.querySelector(".load-more"),p=document.querySelector(".end-message");document.addEventListener("DOMContentLoaded",()=>{n.classList.add("hidden"),p.classList.add("hidden"),g.classList.add("hidden")});const y=()=>{if(!n.querySelector(".loading-message")){const e=document.createElement("span");e.classList.add("loading-message"),e.textContent="Loading images, please wait...",n.appendChild(e)}n.classList.remove("hidden")},L=()=>{const e=n.querySelector(".loading-message");e&&n.removeChild(e),n.classList.add("hidden")},$=()=>{m.innerHTML=""},w=e=>{const t=e.map(a=>`
        <li class="gallery-item">
          <a href="${a.largeImageURL}">
            <img class="gallery-img" src="${a.webformatURL}" alt="${a.tags}" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${a.likes}</p>
            <p><b>Views</b> ${a.views}</p>
            <p><b>Comments</b> ${a.comments}</p>
            <p><b>Downloads</b> ${a.downloads}</p>
          </div>
        </li>`).join("");m.insertAdjacentHTML("beforeend",t),new q(".gallery a").refresh(),g.classList.remove("hidden")},b=()=>{g.classList.add("hidden"),p.classList.remove("hidden")},M=()=>{iziToast.error({title:"Sorry, no images found",message:"Please try again with a different search term."})},x=()=>{const e=m.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})};let i="",l=1;const S=document.querySelector(".form"),u=S.querySelector('input[name="search-text"]'),H=document.querySelector(".load-more");S.addEventListener("submit",async e=>{if(e.preventDefault(),i=u.value.trim(),!i){d.error({title:"Input error",message:"Please enter a search term."});return}u.value="",I(),l=1,y(),$();try{const{hits:t,totalHits:o}=await f(i,l);t.length===0?M():(w(t),(t.length<15||t.length>=o)&&b())}catch{d.error({title:"Error",message:"Something went wrong. Please try again."})}finally{L()}});H.addEventListener("click",async()=>{y();try{l+=1;const{hits:e,totalHits:t}=await f(i,l);e.length>0&&(w(e),x(),(e.length<15||e.length>=t)&&b())}catch{d.error({title:"Error",message:"Something went wrong. Please try again."})}finally{L()}});
//# sourceMappingURL=index.js.map
